[package]
name = "rustLMS"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
gtk = { version = "0.9.6", package = "gtk4" }
glib = "0.20.9"